CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	user_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
	company VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
	phone VARCHAR NOT NULL
);